-- 코드를 입력하세요
SELECT distinct board.WRITER_ID, usr.NICKNAME, CONCAT_WS(" ", CITY, STREET_ADDRESS1, STREET_ADDRESS2), CONCAT_WS("-", SUBSTRING(usr.TLNO, 1, 3), SUBSTRING(usr.TLNO, 4, 4), SUBSTRING(usr.TLNO, 8, 4))
FROM USED_GOODS_BOARD AS board
LEFT JOIN USED_GOODS_USER AS usr ON board.WRITER_ID = usr.USER_ID
WHERE ( 
    SELECT COUNT(*) FROM USED_GOODS_BOARD AS tempb WHERE board.WRITER_ID = tempb.WRITER_ID
) >= 3 
ORDER BY board.WRITER_ID DESC;