-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(s.SALES) as TOTAL_SALES FROM BOOK AS b
JOIN BOOK_SALES AS s ON b.BOOK_ID = s.BOOK_ID
WHERE YEAR(s.SALES_DATE) = 2022 AND MONTH(s.SALES_DATE) = 1
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;